name: Bug report
description: Create a report to help us improve
type: Bug
projects: ['owncloud/338']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      value: |
        1.
        2.
        3.
        ...
      render: textarea
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: A clear and concise description of what happened.
    validations:
      required: true
  - type: textarea
    id: setup
    attributes:
      label: Setup
      description: Please describe how you started the server and provide a list of relevant environment variables or configuration files.
      value: |
        - Web version:
        - oCIS version:
        - browser:

        OCIS_XXX=somevalue
        OCIS_YYY=somevalue
        PROXY_XXX=somevalue
      render: markdown
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: | 
        Add any other context about the problem here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

